export { default as SearchBar } from './SearchBar';
export { default as BgImage } from './BgWrap';
export { default as Banner } from './Banner';
export { default as MidImage } from './MidImage';
export { default as Cate } from './Cate';
export { default as BottomImage } from './BottomImage';
export { default as Promo } from './Promo';
export { default as Section } from './Section';
export { default as Waterfall } from './Waterfall';
